install.packages('remotes')
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install(c('dplyr', 'preprocessCore', 'impute', 'clusterProfiler'))
remotes::install_deps(dep=TRUE)
