install.packages('devtools')
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install(c('preprocessCore', 'impute', 'clusterProfiler', 'dplyr'))
devtools::install_deps(dep=TRUE)
