install.packages('devtools')
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install(c('dplyr', 'Rfast', 'preprocessCore', 'impute', 'clusterProfiler'))
devtools::install_deps(dep=TRUE)
